# Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  
  
  # Position Controllers ---------------------------------------
  joint1_position_controller:
    type: effort_controllers/JointPositionController
    joint: wheel_left_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  joint2_position_controller:
    type: effort_controllers/JointPositionController
    joint: wheel_right_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  
  left_wheel_velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: wheel_left_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  
  right_wheel_velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: wheel_right_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
